"""initial schema

Revision ID: 6e36c99ebd6a
Revises: 
Create Date: 2026-05-29 14:01:31.137833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e36c99ebd6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.Column('board', sa.Enum('SSC', 'ICSE', name='board'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade BETWEEN 5 AND 10', name=op.f('ck_batches_grade_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('name', name=op.f('uq_batches_name'))
    )
    op.create_index('ix_batches_grade_board', 'batches', ['grade', 'board'], unique=False)
    op.create_index(op.f('ix_batches_is_active'), 'batches', ['is_active'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.Enum('STANDARD', 'DIFFICULT', name='subject_difficulty'), server_default='STANDARD', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code')),
    sa.UniqueConstraint('name', name=op.f('uq_subjects_name'))
    )
    op.create_index(op.f('ix_subjects_is_active'), 'subjects', ['is_active'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('teacher_type', sa.Enum('FULL_TIME', 'PART_TIME', name='teacher_type'), server_default='PART_TIME', nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('max_lectures_per_day', sa.SmallInteger(), server_default='6', nullable=False),
    sa.Column('preferred_hours_start', sa.Time(), nullable=True),
    sa.Column('preferred_hours_end', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_lectures_per_day >= 0', name=op.f('ck_teachers_max_lectures_non_negative')),
    sa.CheckConstraint('preferred_hours_end > preferred_hours_start', name=op.f('ck_teachers_preferred_hours_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers'))
    )
    op.create_index(op.f('ix_teachers_full_name'), 'teachers', ['full_name'], unique=False)
    op.create_index(op.f('ix_teachers_is_active'), 'teachers', ['is_active'], unique=False)
    op.create_index(op.f('ix_teachers_teacher_type'), 'teachers', ['teacher_type'], unique=False)
    op.create_index('uq_teachers_email', 'teachers', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_teachers_telegram_chat_id', 'teachers', ['telegram_chat_id'], unique=True, postgresql_where=sa.text('telegram_chat_id IS NOT NULL'))
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'VIEWER', name='user_role'), server_default='MANAGER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('batch_slots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), nullable=False),
    sa.Column('period_index', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_batch_slots_slot_time_order')),
    sa.CheckConstraint('period_index >= 1', name=op.f('ck_batch_slots_period_index_positive')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_slots_batch_id_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_slots')),
    sa.UniqueConstraint('batch_id', 'weekday', 'period_index', name='uq_batch_slots_batch_id_weekday_period_index')
    )
    op.create_index('ix_batch_slots_batch_id_weekday', 'batch_slots', ['batch_id', 'weekday'], unique=False)
    op.create_table('batch_subjects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('weekly_target', sa.SmallInteger(), nullable=False),
    sa.Column('owner_teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weekly_target >= 0', name=op.f('ck_batch_subjects_weekly_target_non_negative')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_batch_subjects_batch_id_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_teacher_id'], ['teachers.id'], name=op.f('fk_batch_subjects_owner_teacher_id_teachers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_batch_subjects_subject_id_subjects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_subjects')),
    sa.UniqueConstraint('batch_id', 'subject_id', name='uq_batch_subjects_batch_id_subject_id')
    )
    op.create_index(op.f('ix_batch_subjects_batch_id'), 'batch_subjects', ['batch_id'], unique=False)
    op.create_table('institution_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), server_default='default', nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'BATCH', name='settings_scope'), server_default='GLOBAL', nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('week_start_day', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), server_default='MON', nullable=False),
    sa.Column('poll_open_time', sa.Time(), server_default=sa.text("'19:00:00'"), nullable=False),
    sa.Column('reminder_offsets_minutes', postgresql.ARRAY(sa.SmallInteger()), server_default=sa.text("'{60,120}'::smallint[]"), nullable=False),
    sa.Column('cutoff_time', sa.Time(), server_default=sa.text("'22:00:00'"), nullable=False),
    sa.Column('solve_time', sa.Time(), server_default=sa.text("'22:15:00'"), nullable=True),
    sa.Column('target_offset_days', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('default_lecture_minutes', sa.SmallInteger(), server_default='60', nullable=False),
    sa.Column('solver_time_limit_seconds', sa.Float(), server_default='10.0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'GLOBAL') = (batch_id IS NULL)", name=op.f('ck_institution_settings_scope_batch')),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_institution_settings_batch_id_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_settings'))
    )
    op.create_index('uq_institution_settings_batch_id', 'institution_settings', ['batch_id'], unique=True, postgresql_where=sa.text('batch_id IS NOT NULL'))
    op.create_index('uq_institution_settings_global', 'institution_settings', ['scope'], unique=True, postgresql_where=sa.text("scope = 'GLOBAL'"))
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='schedule_status'), server_default='DRAFT', nullable=False),
    sa.Column('solver_status', sa.Enum('OPTIMAL', 'FEASIBLE', 'INFEASIBLE', 'UNKNOWN', 'MODEL_INVALID', 'ERROR', name='solver_status'), server_default='UNKNOWN', nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solve_time_ms', sa.Integer(), nullable=True),
    sa.Column('num_unfilled', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('solver_seed', sa.Integer(), nullable=True),
    sa.Column('contract_version', sa.String(length=16), server_default='1', nullable=False),
    sa.Column('solver_input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_size', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_schedules_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], name=op.f('fk_schedules_published_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules')),
    sa.UniqueConstraint('schedule_date', 'version', name='uq_schedules_date_version')
    )
    op.create_index(op.f('ix_schedules_schedule_date'), 'schedules', ['schedule_date'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_table('subject_preferred_windows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), nullable=True),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_subject_preferred_windows_window_order')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_subject_preferred_windows_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_preferred_windows'))
    )
    op.create_index(op.f('ix_subject_preferred_windows_subject_id'), 'subject_preferred_windows', ['subject_id'], unique=False)
    op.create_table('teacher_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('availability_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE_ALL_DAY', 'PARTIAL', 'UNAVAILABLE', name='availability_status'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('TELEGRAM', 'ADMIN', 'DEFAULT', name='availability_source'), server_default='TELEGRAM', nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_availability_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_availability')),
    sa.UniqueConstraint('teacher_id', 'availability_date', name='uq_teacher_availability_teacher_id_availability_date')
    )
    op.create_index('ix_teacher_availability_date_status', 'teacher_availability', ['availability_date', 'status'], unique=False)
    op.create_index(op.f('ix_teacher_availability_is_default'), 'teacher_availability', ['is_default'], unique=False)
    op.create_table('teacher_standard_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_teacher_standard_availability_window_order')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_standard_availability_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_standard_availability'))
    )
    op.create_index('ix_teacher_standard_availability_teacher_id_weekday', 'teacher_standard_availability', ['teacher_id', 'weekday'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('proficiency', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('proficiency BETWEEN 1 AND 5', name=op.f('ck_teacher_subjects_proficiency_range')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_subjects_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_subjects_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id', name=op.f('pk_teacher_subjects'))
    )
    op.create_index(op.f('ix_teacher_subjects_subject_id'), 'teacher_subjects', ['subject_id'], unique=False)
    op.create_table('availability_windows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('availability_id', sa.BigInteger(), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('window_end > window_start', name=op.f('ck_availability_windows_window_order')),
    sa.ForeignKeyConstraint(['availability_id'], ['teacher_availability.id'], name=op.f('fk_availability_windows_availability_id_teacher_availability'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_windows'))
    )
    op.create_index(op.f('ix_availability_windows_availability_id'), 'availability_windows', ['availability_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('schedule_id', sa.BigInteger(), nullable=True),
    sa.Column('availability_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('POLL_OPEN', 'REMINDER', 'CUTOFF_DEFAULT', 'ASSIGNMENT', 'NO_ASSIGNMENT', 'SCHEDULE_PUBLISHED', 'ONBOARDING', name='notification_kind'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'SKIPPED_NO_CHAT', name='notification_status'), server_default='QUEUED', nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempt', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['availability_id'], ['teacher_availability.id'], name=op.f('fk_notification_log_availability_id_teacher_availability'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_notification_log_schedule_id_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_notification_log_teacher_id_teachers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_log')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notification_log_dedupe_key'))
    )
    op.create_index('ix_notification_log_kind_status', 'notification_log', ['kind', 'status'], unique=False)
    op.create_index(op.f('ix_notification_log_schedule_id'), 'notification_log', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_notification_log_target_date'), 'notification_log', ['target_date'], unique=False)
    op.create_index(op.f('ix_notification_log_teacher_id'), 'notification_log', ['teacher_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_slot_id', sa.BigInteger(), nullable=True),
    sa.Column('period_index', sa.SmallInteger(), nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'CONDUCTED', 'CANCELLED', name='entry_status'), server_default='PLANNED', nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_schedule_entries_batch_id_batches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['batch_slot_id'], ['batch_slots.id'], name=op.f('fk_schedule_entries_batch_slot_id_batch_slots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_schedule_entries_schedule_id_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_schedule_entries_subject_id_subjects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_schedule_entries_teacher_id_teachers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_entries')),
    sa.UniqueConstraint('schedule_id', 'batch_id', 'period_index', name='uq_schedule_entries_schedule_id_batch_id_period_index'),
    sa.UniqueConstraint('schedule_id', 'batch_slot_id', name='uq_schedule_entries_schedule_id_batch_slot_id')
    )
    op.create_index('ix_schedule_entries_debt', 'schedule_entries', ['batch_id', 'subject_id', 'status'], unique=False)
    op.create_index(op.f('ix_schedule_entries_schedule_id'), 'schedule_entries', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_status'), 'schedule_entries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_entries_status'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_schedule_id'), table_name='schedule_entries')
    op.drop_index('ix_schedule_entries_debt', table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_notification_log_teacher_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_target_date'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_schedule_id'), table_name='notification_log')
    op.drop_index('ix_notification_log_kind_status', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_availability_windows_availability_id'), table_name='availability_windows')
    op.drop_table('availability_windows')
    op.drop_index(op.f('ix_teacher_subjects_subject_id'), table_name='teacher_subjects')
    op.drop_table('teacher_subjects')
    op.drop_index('ix_teacher_standard_availability_teacher_id_weekday', table_name='teacher_standard_availability')
    op.drop_table('teacher_standard_availability')
    op.drop_index(op.f('ix_teacher_availability_is_default'), table_name='teacher_availability')
    op.drop_index('ix_teacher_availability_date_status', table_name='teacher_availability')
    op.drop_table('teacher_availability')
    op.drop_index(op.f('ix_subject_preferred_windows_subject_id'), table_name='subject_preferred_windows')
    op.drop_table('subject_preferred_windows')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_schedule_date'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index('uq_institution_settings_global', table_name='institution_settings', postgresql_where=sa.text("scope = 'GLOBAL'"))
    op.drop_index('uq_institution_settings_batch_id', table_name='institution_settings', postgresql_where=sa.text('batch_id IS NOT NULL'))
    op.drop_table('institution_settings')
    op.drop_index(op.f('ix_batch_subjects_batch_id'), table_name='batch_subjects')
    op.drop_table('batch_subjects')
    op.drop_index('ix_batch_slots_batch_id_weekday', table_name='batch_slots')
    op.drop_table('batch_slots')
    op.drop_table('users')
    op.drop_index('uq_teachers_telegram_chat_id', table_name='teachers', postgresql_where=sa.text('telegram_chat_id IS NOT NULL'))
    op.drop_index('uq_teachers_email', table_name='teachers', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_teachers_teacher_type'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_is_active'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_full_name'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_subjects_is_active'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_batches_is_active'), table_name='batches')
    op.drop_index('ix_batches_grade_board', table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###

    # autogenerate omits DROP TYPE for native enums (open question #9) — drop them
    # explicitly so the downgrade fully reverses the upgrade.
    for enum_name in (
        "board",
        "weekday",
        "teacher_type",
        "subject_difficulty",
        "availability_status",
        "availability_source",
        "settings_scope",
        "schedule_status",
        "solver_status",
        "entry_status",
        "notification_kind",
        "notification_status",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
